name: tests
on: pull_request
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run sleep
        run: sleep 10
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
      - name: checkout
        if: success()
        uses: actions/checkout@v2
      - name: merge
        if: success()
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'fix'
          target: 'main'
          # webhook_url: #if present add the Slack webhook